name: goreleaser

on:
  push:
    tags:
      - v*.*.*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
